/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author newuser
 */
public class Fase extends Pvirgen {

   

    Fase(int i) {
        initComponents();
        this.setSize(1151, 662);
        switch (i){
            case 0:
                
                break;
            case 1:
                Info.jmformulario.setEnabled(true);
                bAbrirInscripcion.setEnabled(false);
                bCerrarInscripcion.setEnabled(true); 
                break;
            case 2:
                Info.jmformulario.setEnabled(false);
                Info.jmdetalles.setEnabled(true);
                Info.jmlistado.setEnabled(true);
                bAbrirInscripcion.setEnabled(false);
                bCerrarInscripcion.setEnabled(false);
                bEjecutarSorteo.setEnabled(true);
                break;
            case 3:
                bAbrirInscripcion.setEnabled(false);
                bCerrarInscripcion.setEnabled(false);
                bEjecutarSorteo.setEnabled(false);
                break;
            
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bCerrarInscripcion = new javax.swing.JButton();
        bEjecutarSorteo = new javax.swing.JButton();
        bAbrirInscripcion = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1151, 662));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Fases");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fases del programa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N

        bCerrarInscripcion.setText("Cerrar inscripciones");
        bCerrarInscripcion.setEnabled(false);
        bCerrarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarInscripcionActionPerformed(evt);
            }
        });

        bEjecutarSorteo.setText("Ejecutar sorteo");
        bEjecutarSorteo.setEnabled(false);
        bEjecutarSorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEjecutarSorteoActionPerformed(evt);
            }
        });

        bAbrirInscripcion.setText("Abrir inscripciones");
        bAbrirInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirInscripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAbrirInscripcion)
                    .addComponent(bEjecutarSorteo)
                    .addComponent(bCerrarInscripcion))
                .addContainerGap(549, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAbrirInscripcion)
                .addGap(18, 18, 18)
                .addComponent(bCerrarInscripcion)
                .addGap(18, 18, 18)
                .addComponent(bEjecutarSorteo)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel1)))
                .addContainerGap(430, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(397, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAbrirInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirInscripcionActionPerformed

        Cvista.estadofase(1);
        
    }//GEN-LAST:event_bAbrirInscripcionActionPerformed

    private void bCerrarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarInscripcionActionPerformed

        Cvista.estadofase(2);
        
    }//GEN-LAST:event_bCerrarInscripcionActionPerformed

    private void bEjecutarSorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEjecutarSorteoActionPerformed

        Cvista.estadofase(3);
        
    }//GEN-LAST:event_bEjecutarSorteoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbrirInscripcion;
    private javax.swing.JButton bCerrarInscripcion;
    private javax.swing.JButton bEjecutarSorteo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
