/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Exceptions.*;
import betaproyecto.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Formulario extends Pvirgen {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        this.setSize(1151, 662);
        //Rellenar provincia
        //comboPro.addItem(BETAPROYECTO.cogerprovincia());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgCentroEnsenanza = new javax.swing.ButtonGroup();
        bgModelo = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ftDniNen = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rbHombre = new javax.swing.JRadioButton();
        rbMujer = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfNombreNen = new javax.swing.JTextField();
        tfPrimerApellidoNen = new javax.swing.JTextField();
        tfSegundoApellidoNen = new javax.swing.JTextField();
        dcFecha = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ftDniTutor = new javax.swing.JFormattedTextField();
        tfNombreTutor = new javax.swing.JTextField();
        tfPrimerApellidoTutor = new javax.swing.JTextField();
        tfSegundoApellidoTutor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        comboMu = new javax.swing.JComboBox();
        comboLoc = new javax.swing.JComboBox();
        tfCalle = new javax.swing.JTextField();
        ftCp = new javax.swing.JFormattedTextField();
        comboNum = new javax.swing.JComboBox();
        ftTlfnoUno = new javax.swing.JFormattedTextField();
        cTlfnoUno = new javax.swing.JCheckBox();
        ftTlfnoDos = new javax.swing.JFormattedTextField();
        cTlfnoDos = new javax.swing.JCheckBox();
        ftTlfnoTres = new javax.swing.JFormattedTextField();
        cTlfnoTres = new javax.swing.JCheckBox();
        ftTlfnoCuatro = new javax.swing.JFormattedTextField();
        cTlfnoCuatro = new javax.swing.JCheckBox();
        bLupaCalle = new javax.swing.JButton();
        ftLetra = new javax.swing.JFormattedTextField();
        ftEscalera = new javax.swing.JFormattedTextField();
        ftPiso = new javax.swing.JFormattedTextField();
        ftMano = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        comboPro = new javax.swing.JComboBox();
        bBorrarDireccion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        rAlava = new javax.swing.JRadioButton();
        rFueraAlava = new javax.swing.JRadioButton();
        bLupaCentro = new javax.swing.JButton();
        tfCentro = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        rModeloB = new javax.swing.JRadioButton();
        rModeloA = new javax.swing.JRadioButton();
        rModeloD = new javax.swing.JRadioButton();
        cDiscapacidad = new javax.swing.JCheckBox();
        bBorrar = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        bProtección = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1151, 662));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del participante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gulim", 0, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel5.setText("Dni");

        try {
            ftDniNen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftDniNen.setEnabled(false);
        ftDniNen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftDniNenActionPerformed(evt);
            }
        });

        jLabel6.setText("*Nombre");

        jLabel8.setText("*Primer apellido");

        jLabel9.setText("*Segundo apellido");

        jLabel10.setText("*Sexo");

        rbHombre.setBackground(new java.awt.Color(255, 255, 255));
        bgSexo.add(rbHombre);
        rbHombre.setText("Hombre");
        rbHombre.setEnabled(false);
        rbHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHombreActionPerformed(evt);
            }
        });

        rbMujer.setBackground(new java.awt.Color(255, 255, 255));
        bgSexo.add(rbMujer);
        rbMujer.setText("Mujer");
        rbMujer.setEnabled(false);
        rbMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMujerActionPerformed(evt);
            }
        });

        jLabel11.setText("Fecha de nacimiento");

        jLabel12.setText("dd/mm/aaaa");

        tfNombreNen.setEnabled(false);

        tfPrimerApellidoNen.setEnabled(false);

        tfSegundoApellidoNen.setEnabled(false);

        dcFecha.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSegundoApellidoNen, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jLabel8))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel11))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(rbHombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbMujer))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPrimerApellidoNen, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ftDniNen, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfNombreNen, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ftDniNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfNombreNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfPrimerApellidoNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfSegundoApellidoNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbHombre)
                        .addComponent(rbMujer)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del padre/madre o tutor/a", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gulim", 0, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel7.setText("*Dni");

        jLabel2.setText("*Primer apellido/Razón Social");

        jLabel3.setText("*Segundo apellido");

        jLabel4.setText("*Nombre");

        try {
            ftDniTutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftDniTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftDniTutorActionPerformed(evt);
            }
        });

        tfNombreTutor.setEnabled(false);

        tfPrimerApellidoTutor.setEnabled(false);

        tfSegundoApellidoTutor.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ftDniTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNombreTutor, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                    .addComponent(tfPrimerApellidoTutor)
                    .addComponent(tfSegundoApellidoTutor, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ftDniTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfNombreTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPrimerApellidoTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfSegundoApellidoTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gulim", 0, 14), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("*Municipio");

        jLabel14.setText("*Localidad");

        jLabel15.setText("*Código postal");

        jLabel16.setText("*Calle");

        jLabel17.setText("Número");

        jLabel18.setText("Escalera");

        jLabel19.setText("Letra");

        jLabel20.setText("Piso");

        jLabel99.setText("Mano");

        jLabel21.setText("Teléfono");

        comboMu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adios", "adios" }));
        comboMu.setSelectedIndex(-1);
        comboMu.setEnabled(false);
        comboMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMuActionPerformed(evt);
            }
        });

        comboLoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "epa", "Epa" }));
        comboLoc.setSelectedIndex(-1);
        comboLoc.setEnabled(false);
        comboLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLocActionPerformed(evt);
            }
        });

        tfCalle.setEditable(false);
        tfCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCalleActionPerformed(evt);
            }
        });

        try {
            ftCp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftCp.setEnabled(false);
        ftCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftCpActionPerformed(evt);
            }
        });

        comboNum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2" }));
        comboNum.setSelectedIndex(-1);
        comboNum.setEnabled(false);
        comboNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumActionPerformed(evt);
            }
        });

        try {
            ftTlfnoUno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftTlfnoUno.setEnabled(false);

        cTlfnoUno.setEnabled(false);
        cTlfnoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTlfnoUnoActionPerformed(evt);
            }
        });

        try {
            ftTlfnoDos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftTlfnoDos.setEnabled(false);

        cTlfnoDos.setEnabled(false);
        cTlfnoDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTlfnoDosActionPerformed(evt);
            }
        });

        try {
            ftTlfnoTres.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftTlfnoTres.setEnabled(false);

        cTlfnoTres.setEnabled(false);
        cTlfnoTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTlfnoTresActionPerformed(evt);
            }
        });

        try {
            ftTlfnoCuatro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftTlfnoCuatro.setEnabled(false);

        cTlfnoCuatro.setEnabled(false);
        cTlfnoCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTlfnoCuatroActionPerformed(evt);
            }
        });

        bLupaCalle.setText("lupa");
        bLupaCalle.setEnabled(false);
        bLupaCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLupaCalleActionPerformed(evt);
            }
        });

        try {
            ftLetra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftLetra.setEnabled(false);
        ftLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftLetraActionPerformed(evt);
            }
        });

        try {
            ftEscalera.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftEscalera.setEnabled(false);
        ftEscalera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftEscaleraActionPerformed(evt);
            }
        });

        try {
            ftPiso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftPiso.setEnabled(false);
        ftPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftPisoActionPerformed(evt);
            }
        });

        try {
            ftMano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftMano.setEnabled(false);
        ftMano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftManoActionPerformed(evt);
            }
        });

        jLabel24.setText("*Povincia");

        comboPro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alava", "Gipuzkoa" }));
        comboPro.setSelectedIndex(-1);
        comboPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProActionPerformed(evt);
            }
        });

        bBorrarDireccion.setText("Borrar dirección");
        bBorrarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarDireccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(comboMu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ftTlfnoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cTlfnoUno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ftTlfnoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cTlfnoDos)
                                        .addGap(22, 22, 22))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ftLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(147, 147, 147)))
                                .addComponent(ftTlfnoTres, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cTlfnoTres)
                                .addGap(18, 18, 18)
                                .addComponent(ftTlfnoCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cTlfnoCuatro))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboPro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addComponent(comboLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel16)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(tfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bLupaCalle))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(ftEscalera, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ftPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel99)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ftMano, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBorrarDireccion)
                    .addComponent(ftCp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(187, 187, 187))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(comboMu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(comboPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(comboLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLupaCalle))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel99)
                            .addComponent(comboNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftEscalera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftMano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ftTlfnoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)
                                .addComponent(cTlfnoUno))
                            .addComponent(ftTlfnoDos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftTlfnoTres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cTlfnoDos)
                            .addComponent(cTlfnoTres)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ftTlfnoCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cTlfnoCuatro)
                        .addComponent(bBorrarDireccion)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Otros datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gulim", 0, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel22.setText("*Centro de Enseñanza");

        rAlava.setBackground(new java.awt.Color(255, 255, 255));
        bgCentroEnsenanza.add(rAlava);
        rAlava.setText("Álava");
        rAlava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAlavaActionPerformed(evt);
            }
        });

        rFueraAlava.setBackground(new java.awt.Color(255, 255, 255));
        bgCentroEnsenanza.add(rFueraAlava);
        rFueraAlava.setText("Fuera de Álava");
        rFueraAlava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rFueraAlavaActionPerformed(evt);
            }
        });

        bLupaCentro.setText("lupa");
        bLupaCentro.setEnabled(false);
        bLupaCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLupaCentroActionPerformed(evt);
            }
        });

        tfCentro.setEditable(false);
        tfCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCentroActionPerformed(evt);
            }
        });

        jLabel23.setText("*Modelo");

        rModeloB.setBackground(new java.awt.Color(255, 255, 255));
        bgModelo.add(rModeloB);
        rModeloB.setText("B");
        rModeloB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rModeloBActionPerformed(evt);
            }
        });

        rModeloA.setBackground(new java.awt.Color(255, 255, 255));
        bgModelo.add(rModeloA);
        rModeloA.setText("A");
        rModeloA.setToolTipText("");
        rModeloA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rModeloAActionPerformed(evt);
            }
        });

        rModeloD.setBackground(new java.awt.Color(255, 255, 255));
        bgModelo.add(rModeloD);
        rModeloD.setText("D");
        rModeloD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rModeloDActionPerformed(evt);
            }
        });

        cDiscapacidad.setText("Discapacidad");
        cDiscapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDiscapacidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rAlava)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rFueraAlava))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(rModeloA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rModeloB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rModeloD)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bLupaCentro))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(cDiscapacidad)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(rAlava)
                    .addComponent(rFueraAlava)
                    .addComponent(tfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLupaCentro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(rModeloA)
                    .addComponent(rModeloB)
                    .addComponent(rModeloD)
                    .addComponent(cDiscapacidad))
                .addGap(32, 32, 32))
        );

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bProtección.setText("Protección datos personales");
        bProtección.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProtecciónActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Solicitud Inscripción");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(157, 157, 157))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(bBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bGuardar)
                                .addGap(48, 48, 48))
                            .addComponent(bProtección, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(91, 91, 91))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(524, 524, 524)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bBorrar)
                            .addComponent(bGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bProtección))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbHombreActionPerformed

    private void rbMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMujerActionPerformed

    private void comboMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMuActionPerformed
        
        comboPro.setEnabled(false);
        if(comboMu.getSelectedIndex() != -1){            
            ftCp.setEnabled(true);
        }
        //Rellenar localidad
        //comboLoc.addItem(BETAPROYECTO.cogerlocalidad());
    }//GEN-LAST:event_comboMuActionPerformed

    private void comboLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocActionPerformed
        ftCp.setEnabled(false);
        if(comboLoc.getSelectedIndex() != -1){            
            bLupaCalle.setEnabled(true);
        } 
        //Rellenar numero
        //comboNum.addItem(BETAPROYECTO.cogernumero());
    }//GEN-LAST:event_comboLocActionPerformed

    private void tfCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCalleActionPerformed
   
    }//GEN-LAST:event_tfCalleActionPerformed
    
    
    
    private void comboNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumActionPerformed
        bLupaCalle.setEnabled(false);
        if(comboNum.getSelectedIndex() != -1){
            ftLetra.setEnabled(true);
            ftEscalera.setEnabled(true);
            ftPiso.setEnabled(true);
            ftMano.setEnabled(true);            
        }
    }//GEN-LAST:event_comboNumActionPerformed

    private void cTlfnoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTlfnoUnoActionPerformed
        if(cTlfnoUno.isSelected()){
            ftTlfnoDos.setEnabled(true);
            cTlfnoDos.setEnabled(true);
        }
    }//GEN-LAST:event_cTlfnoUnoActionPerformed

    private void cTlfnoDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTlfnoDosActionPerformed
        if(cTlfnoDos.isSelected()){
            ftTlfnoTres.setEnabled(true);
            cTlfnoTres.setEnabled(true);
        }
    }//GEN-LAST:event_cTlfnoDosActionPerformed

    private void cTlfnoTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTlfnoTresActionPerformed
        if(cTlfnoTres.isSelected()){
            ftTlfnoCuatro.setEnabled(true);
            cTlfnoCuatro.setEnabled(true);
        }
    }//GEN-LAST:event_cTlfnoTresActionPerformed

    private void cTlfnoCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTlfnoCuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTlfnoCuatroActionPerformed

    private void ftLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftLetraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftLetraActionPerformed

    private void ftEscaleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftEscaleraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftEscaleraActionPerformed

    private void ftPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftPisoActionPerformed

    private void ftManoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftManoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftManoActionPerformed

    private void rAlavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAlavaActionPerformed
        if(rAlava.isSelected()){
            bLupaCentro.setEnabled(true);
        }
        //BETAPROYECTO.centroalava();
    }//GEN-LAST:event_rAlavaActionPerformed

    private void rFueraAlavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rFueraAlavaActionPerformed
        if(rFueraAlava.isSelected()){
            bLupaCentro.setEnabled(true);
        }
        //BETAPROYECTO.centrofueraalava();
    }//GEN-LAST:event_rFueraAlavaActionPerformed

    private void tfCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCentroActionPerformed

    private void rModeloBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rModeloBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rModeloBActionPerformed

    private void rModeloAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rModeloAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rModeloAActionPerformed

    private void rModeloDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rModeloDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rModeloDActionPerformed

    private void cDiscapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDiscapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDiscapacidadActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        
        Info.jmformulario.doClick();
        
    }//GEN-LAST:event_bBorrarActionPerformed

    private void comboProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProActionPerformed
        
        if(comboPro.getSelectedIndex() != -1){
            rAlava.setText(comboPro.getSelectedItem().toString());
            rFueraAlava.setText("Fuera de " + comboPro.getSelectedItem().toString());
            comboMu.setEnabled(true);
        }
        //Rellenar municipio
        //comboMu.addItem(BETAPROYECTO.cogermunicipio(comboPro.getSelectedItem().toString()));
        
    }//GEN-LAST:event_comboProActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        int discapacidad = 0;        
        if(cDiscapacidad.isSelected()){
            discapacidad = 1;
        }
        
        int sexo = 9;
        if(rbHombre.isSelected()){
            sexo = 0;
        }
        else if(rbMujer.isSelected()){
            sexo = 1;
        }
        
        String modelo = "";
        if(rModeloA.isSelected()){
            modelo = "A";
        }
        else if(rModeloB.isSelected()){
            modelo = "B";
        }
        else if(rModeloD.isSelected()){
            modelo = "D";
        } 
        
        try {
            //Hay que crear en el constructor el metodo de buscarnen-------------------------
            //Object busqueda = BETAPROYECTO.buscarnen(ftDniNen.getText());
            //if(busqueda/*.getdni() */ == null){
            if(validardatos()){
                /*BETAPROYECTO.guardar(ftDniTutor.getText(), tfNombreTutor.getText(), tfPrimerApellidoTutor.getText(), tfSegundoApellidoTutor.getText(),
                ftDniNen.getText(), tfNombreNen.getText(), tfPrimerApellidoNen.getText(), tfSegundoApellidoNen.getText(), sexo, dcFecha.getCalendar(),
                comboPro.getSelectedIndex(), comboMu.getSelectedIndex(), ftCp.getText(), comboLoc.getSelectedIndex(), tfCalle.getText(),
                comboNum.getSelectedIndex(), ftLetra.getText(), ftEscalera.getText(), ftPiso.getText(), ftMano.getText(),
                ftTlfnoUno.getText(), ftTlfnoDos.getText(), ftTlfnoTres.getText(), ftTlfnoCuatro.getText(),
                tfCentro.getText(), modelo, discapacidad);*/                
                
                Cvista.guardar();            
            }
            //}
            //else{
            //    javax.swing.JOptionPane.showMessageDialog(this, "El Dni del niño esta repetido");
            //}
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bProtecciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProtecciónActionPerformed
        Cvista.protecciondatos();
    }//GEN-LAST:event_bProtecciónActionPerformed

    private void bLupaCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLupaCalleActionPerformed
        comboLoc.setEnabled(false);
        comboNum.setEnabled(true);
        ftTlfnoUno.setEnabled(true);
        cTlfnoUno.setEnabled(true);
        
        //Object = BETAPROYECTO.cojercalle();
        Cvista.calles(/*Object*/);        
    }//GEN-LAST:event_bLupaCalleActionPerformed

    private void bLupaCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLupaCentroActionPerformed
        
        //Object = BETAPROYECTO.cogercentro();
        Cvista.centros(/*Object*/);
        
    }//GEN-LAST:event_bLupaCentroActionPerformed

    private void bBorrarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarDireccionActionPerformed
        comboPro.setSelectedIndex(-1);
        comboMu.setSelectedIndex(-1);
        ftCp.setText(null);
        comboLoc.setSelectedIndex(-1);
        tfCalle.setText(null);
        comboNum.setSelectedIndex(-1);
        ftLetra.setText(null);
        ftEscalera.setText(null);
        ftPiso.setText(null);
        ftMano.setText(null);
        ftTlfnoUno.setText(null);
        cTlfnoUno.setSelected(false);
        ftTlfnoDos.setText(null);
        cTlfnoDos.setSelected(false);
        ftTlfnoTres.setText(null);
        cTlfnoTres.setSelected(false);
        ftTlfnoCuatro.setText(null);
        cTlfnoCuatro.setSelected(false);
        
        borrardireccion();
        
    }//GEN-LAST:event_bBorrarDireccionActionPerformed

    private void ftDniNenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftDniNenActionPerformed
        
        validarDni(ftDniNen.getText());        
        
    }//GEN-LAST:event_ftDniNenActionPerformed

    private void ftCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftCpActionPerformed
        comboMu.setEnabled(false);
        comboLoc.setEnabled(true);
    }//GEN-LAST:event_ftCpActionPerformed

    private void ftDniTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftDniTutorActionPerformed

        if(validarDni(ftDniTutor.getText())){
            Object busqueda = BETAPROYECTO.buscartutor(ftDniTutor.getText());
            if(busqueda/*.getdni() */== null){
                tfNombreTutor.setEnabled(true);
                tfPrimerApellidoTutor.setEnabled(true);
                tfSegundoApellidoTutor.setEnabled(true);
                ftDniNen.setEnabled(true);
                tfNombreNen.setEnabled(true);
                tfPrimerApellidoNen.setEnabled(true);
                tfSegundoApellidoNen.setEnabled(true);
                rbHombre.setEnabled(true);
                rbMujer.setEnabled(true);
                dcFecha.setEnabled(true);
            }
            else{
                //tfNombreTutor.setText(busqueda.getnombre().toString());
                //tfSegundoApellidoTutor.setText(busqueda.getape1().toString());
                //tfPrimerApellidoTutor.setText(busqueda.getape2().toString());
                ftDniNen.setEnabled(true);
                tfNombreNen.setEnabled(true);
                tfPrimerApellidoNen.setEnabled(true);
                tfSegundoApellidoNen.setEnabled(true);
                rbHombre.setEnabled(true);
                rbMujer.setEnabled(true);
                dcFecha.setEnabled(true);
            }
        }
    }//GEN-LAST:event_ftDniTutorActionPerformed

    private Boolean validarDni(String DniTutor) {
        boolean validacion = Cvista.validardni(DniTutor);
        return validacion;
    }
    
    private boolean validardatos() throws Exception {
        try{
            camposvacios();
            validarFecha();
            
            return true;
        }
        catch(CampoVacio e)
        {
            javax.swing.JOptionPane.showMessageDialog(this,e.getMensaje());
            return false;
        }
        catch(FechaNoValida e)
        {
            javax.swing.JOptionPane.showMessageDialog(this,e.getMensaje());
            return false;
        }
        
    }
    
    private void borrardireccion(){
        comboPro.setEnabled(true);
        comboNum.setEnabled(false);
        ftLetra.setEnabled(false);
        ftEscalera.setEnabled(false);
        ftPiso.setEnabled(false);
        ftMano.setEnabled(false);
        ftTlfnoUno.setEnabled(false);
        cTlfnoUno.setEnabled(false);
        ftTlfnoDos.setEnabled(false);
        cTlfnoDos.setEnabled(false);
        ftTlfnoTres.setEnabled(false);
        cTlfnoTres.setEnabled(false);
        ftTlfnoCuatro.setEnabled(false);
        cTlfnoCuatro.setEnabled(false);
    }
    
    private void validarFecha()throws Exception{
        if (dcFecha.getDate() == null)
            throw new CampoVacio("El fecha es un dato obligatorio"); 
        
        Calendar hoy = Calendar.getInstance();
        Calendar fechaEvento = dcFecha.getCalendar();        
        
        if (fechaEvento.after(hoy))
                throw new FechaNoValida("La fecha tiene que se inferior a la actual"); 
        hoy.add(Calendar.YEAR, -16);
        if (fechaEvento.before(hoy))
                throw new FechaNoValida("El participante no puede ser mayor de 16 años");     
    }
    
    private void camposvacios() throws Exception{
        if (ftDniTutor.getValue() == null)
           throw new CampoVacio("El Dni del tutor es un dato obligatorio");
        if (tfNombreTutor.getText().equals("") == true)
            throw new CampoVacio("El nombre del tutor es un dato obligatorio");
        if (tfPrimerApellidoTutor.getText().equals("") == true)
            throw new CampoVacio("El primer apellido del tutor es un dato obligatorio");
        if (tfSegundoApellidoTutor.getText().equals("") == true)
            throw new CampoVacio("El segundo apellido del tutor es un dato obligatorio");
        if (tfNombreNen.getText().equals("") == true)
            throw new CampoVacio("El nombre del niño es un dato obligatorio");
        if (tfPrimerApellidoNen.getText().equals("") == true)
            throw new CampoVacio("El primer apellido de niño es un dato obligatorio");
        if (tfSegundoApellidoNen.getText().equals("") == true)
            throw new CampoVacio("El segundo apellido del niño es un dato obligatorio");
        if(bgSexo.isSelected(rbHombre.getModel()) == false && bgSexo.isSelected(rbMujer.getModel()) == false)
            throw new CampoVacio("El sexo del niño es un dato obligatorio");
        if(comboPro.getSelectedIndex() == -1)
            throw new CampoVacio("La provincia es un dato obligatorio");
        if(comboMu.getSelectedIndex() == -1)
            throw new CampoVacio("El municipio es un dato obligatorio");
        if(ftCp.getValue() == null)
            throw new CampoVacio("El codigo postal es un dato obligatorio");
        if(comboLoc.getSelectedIndex() == -1)
            throw new CampoVacio("La localidad es un dato obligatorio");
        if(tfCalle.getText().equals("") == true)
            throw new CampoVacio("La calle es un dato obligatorio");
        if(ftTlfnoUno.getValue() == null)
            throw new CampoVacio("El primer telefono es un dato obligatorio");
        if(cTlfnoUno.isSelected() == false)
            throw new CampoVacio("Hay que activar el checkbox del primer telefono");
        if(tfCentro.getText().equals("") == true)
            throw new CampoVacio("El centro de enseñanza es un dato obligatorio");        
        if(rModeloA.isSelected() == false && rModeloB.isSelected() == false && rModeloD.isSelected() == false)
            throw new CampoVacio("El modelo es un dato obligatorio");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bBorrarDireccion;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bLupaCalle;
    private javax.swing.JButton bLupaCentro;
    private javax.swing.JButton bProtección;
    private javax.swing.ButtonGroup bgCentroEnsenanza;
    private javax.swing.ButtonGroup bgModelo;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JCheckBox cDiscapacidad;
    private javax.swing.JCheckBox cTlfnoCuatro;
    private javax.swing.JCheckBox cTlfnoDos;
    private javax.swing.JCheckBox cTlfnoTres;
    private javax.swing.JCheckBox cTlfnoUno;
    private javax.swing.JComboBox comboLoc;
    private javax.swing.JComboBox comboMu;
    private javax.swing.JComboBox comboNum;
    private javax.swing.JComboBox comboPro;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JFormattedTextField ftCp;
    private javax.swing.JFormattedTextField ftDniNen;
    private javax.swing.JFormattedTextField ftDniTutor;
    private javax.swing.JFormattedTextField ftEscalera;
    private javax.swing.JFormattedTextField ftLetra;
    private javax.swing.JFormattedTextField ftMano;
    private javax.swing.JFormattedTextField ftPiso;
    private javax.swing.JFormattedTextField ftTlfnoCuatro;
    private javax.swing.JFormattedTextField ftTlfnoDos;
    private javax.swing.JFormattedTextField ftTlfnoTres;
    private javax.swing.JFormattedTextField ftTlfnoUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton rAlava;
    private javax.swing.JRadioButton rFueraAlava;
    private javax.swing.JRadioButton rModeloA;
    private javax.swing.JRadioButton rModeloB;
    private javax.swing.JRadioButton rModeloD;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMujer;
    public static javax.swing.JTextField tfCalle;
    public static javax.swing.JTextField tfCentro;
    private javax.swing.JTextField tfNombreNen;
    private javax.swing.JTextField tfNombreTutor;
    private javax.swing.JTextField tfPrimerApellidoNen;
    private javax.swing.JTextField tfPrimerApellidoTutor;
    private javax.swing.JTextField tfSegundoApellidoNen;
    private javax.swing.JTextField tfSegundoApellidoTutor;
    // End of variables declaration//GEN-END:variables

    
}
